test:
    step_a:
        CleanerA: cleanfreak.cleaners.testcleaners
        CleanerB: cleanfreak.cleaners.testcleaners
        CleanerC: cleanfreak.cleaners.testcleaners
        CleanerD: cleanfreak.cleaners.testcleaners
        CleanerE: cleanfreak.cleaners.testcleaners
    step_b:
        CleanerC: cleanfreak.cleaners.testcleaners
        CleanerD: cleanfreak.cleaners.testcleaners
    step_c:
        CleanerA: cleanfreak.cleaners.testcleaners
        CleanerC: cleanfreak.cleaners.testcleaners
        CleanerE: cleanfreak.cleaners.testcleaners
